// admin-lang.js - 后台完整语言包

const adminLang = {
    current: 'en',  // 默认英文
    
    // ========== 英文 ==========
    en: {
        // ----- 菜单 -----
        'menu_dashboard': 'Admin Dashboard',
        'menu_users': 'User Management',
        'menu_kyc': 'KYC Verification',
        'menu_emailverify': 'Email Verification',
        'menu_trial': 'Trial Bonus',
        'menu_withdrawals': 'Withdrawal',
        'menu_vip': 'VIP Settings',
        'menu_setorders': 'Orders Trigger',
        'menu_orders': 'Orders History',
        'menu_orderpool': 'Orders Pool',
        'menu_animated': 'Animated',
        'menu_signin': 'Check In Bonus',
        'menu_certificate': 'Certificate',
        'menu_content': 'Content',
        'menu_logout': 'Log Out',
        
        // ----- 通用按钮 -----
        'btn_search': 'Search',
        'btn_refresh': 'Refresh',
        'btn_add': 'Add',
        'btn_save': 'Save',
        'btn_cancel': 'Cancel',
        'btn_edit': 'Edit',
        'btn_delete': 'Delete',
        'btn_confirm': 'Confirm',
        'btn_create': 'Create',
        'btn_upload': 'Upload',
        'btn_preview': 'Preview',
        'btn_close': 'Close',
        'btn_back': 'Back',
        'btn_topup': 'Top Up',
        'btn_cut': 'Deduct',
        'btn_modify': 'Modify',
        'btn_reset': 'Reset',
        'btn_approve': 'Approve',
        'btn_reject': 'Reject',
        'btn_set_code': 'Set Code',
        'btn_release': 'Release',
        'btn_release_now': 'Release Now',
        'btn_bind': 'Bind Address',
        'btn_withdraw': 'Request Withdrawal',
        'btn_claim': 'Claim Reward',
        'btn_copy': 'Copy',
        
        // ----- 表格表头 -----
        'th_uid': 'UID',
        'th_username': 'Username',
        'th_phone': 'Phone',
        'th_balance': 'Balance',
        'th_trial': 'Trial Bonus',
        'th_vip': 'VIP Level',
        'th_wallet': 'Wallet Address',
        'th_action': 'Actions',
        'th_order_no': 'Order No',
        'th_hotel': 'Hotel Name',
        'th_price': 'Price',
        'th_image': 'Image',
        'th_status': 'Status',
        'th_created': 'Created',
        'th_commission': 'Commission',
        'th_buyer': 'Buyer',
        'th_invite_code': 'Invite Code',
        'th_referrer': 'Referrer',
        'th_document_type': 'Document Type',
        'th_uploaded_at': 'Uploaded At',
        'th_email': 'Email',
        'th_request_time': 'Request Time',
        'th_verification_code': 'Verification Code',
        'th_amount': 'Amount',
        'th_request_date': 'Request Date',
        'th_level': 'Level',
        'th_rank_name': 'Rank Name',
        'th_orders_limit': 'Orders Limit',
        'th_commission_rate': 'Commission Rate (%)',
        'th_required_deposit': 'Required Deposit (€)',
        'th_product_name': 'Product Name',
        'th_total_price': 'Total Price',
        'th_total_commission': 'Total Commission',
        'th_order_code': 'Order Code',
        'th_accommodation_name': 'Accommodation Name',
        'th_video_url': 'Video / GIF URL',
        'th_image_url': 'Image URL',
        'th_certificate_image': 'Certificate Image',
        'th_title': 'Title',
        'th_content': 'Content',
        'th_products': 'Products',
        
        // ----- 状态 -----
        'status_pending': 'Pending',
        'status_approved': 'Approved',
        'status_rejected': 'Rejected',
        'status_available': 'Available',
        'status_unavailable': 'Unavailable',
        'status_active': 'Active',
        'status_inactive': 'Inactive',
        'status_verified': 'Verified',
        'status_unverified': 'Unverified',
        'status_processing': 'Processing',
        'status_delivered': 'Delivered',
        'status_cancelled': 'Cancelled',
        
        // ----- 页面标题 -----
        'title_dashboard': 'Dashboard',
        'title_users': 'User Management',
        'title_kyc': 'KYC Verification',
        'title_emailverify': 'Email Verification',
        'title_trial': 'Trial Bonus Management',
        'title_withdrawals': 'Withdrawal Review',
        'title_vip': 'VIP Settings',
        'title_setorders': 'Orders Trigger',
        'title_orders': 'Orders History',
        'title_orderpool': 'Orders Pool',
        'title_animated': 'Animated / Video',
        'title_signin': 'Check In Bonus',
        'title_certificate': 'Certificate',
        'title_content': 'Content Management',
        
        // ----- 仪表板 -----
        'today': 'Today',
        'days7': '7 Days',
        'days30': '30 Days',
        'pending_kyc': 'Pending KYC',
        'pending_withdrawal': 'Pending Withdrawal',
        'pending_email': 'Pending Email',
        'order_pool_total': 'Orders Pool',
        'new_users_today': 'New Users Today',
        'total_users': 'Total Users',
        'total_deposit': 'Total Deposit',
        'total_withdraw': 'Total Withdraw',
        'deposit_withdraw_trend': 'Deposit & Withdrawal Trend',
        'deposit': 'Deposit',
        'withdraw': 'Withdraw',
        'onboarding_progress': 'Onboarding Progress',
        'completed_3_3': 'Completed (3/3)',
        'realtime_activity': 'Realtime Activity',
        'live_update': 'Live Update',
        'loading': 'Loading...',
        'no_activity': 'No activity',
        
        // ----- 用户管理 -----
        'create_user_title': 'Create New User',
        'edit_user_title': 'Edit User',
        'phone_placeholder': 'Phone Number',
        'username_placeholder': 'Username',
        'password_placeholder': 'Password',
        'password_leave_empty': 'Leave empty to keep current',
        'pin_4_digits': '4-digit PIN',
        'onboarding_status': 'Onboarding Status',
        'not_started': 'Not Started',
        'completed': 'Completed',
        'steps': 'Steps',
        'topup_amount': 'Top Up Amount (€)',
        'bonus_amount': 'Bonus Amount (€) - optional',
        'cut_amount': 'Deduction Amount (€)',
        'enter_topup_amount': 'Please enter Top Up amount',
        'enter_bonus_amount': 'Please enter Bonus amount',
        'enter_cut_amount': 'Please enter deduction amount',
        'confirm_topup': 'Confirm Top Up',
        'confirm_cut': 'Confirm Deduction',
        'user_balance_info': 'User: {user} | New balance: €{balance}',
        
        // ----- KYC -----
        'pending_review': 'Pending Review',
        'verified_records': 'Verified Records',
        'national_id_front': 'ID Front',
        'national_id_back': 'ID Back',
        'passport': 'Passport',
        'residence_permit': 'Residence Permit',
        'submit_time': 'Submit Time',
        'verification_time': 'Verification Time',
        'approve_kyc': 'Approve',
        'reject_kyc': 'Reject',
        'delete_kyc': 'Delete Record',
        'kyc_approved_success': 'KYC approved successfully',
        'kyc_rejected': 'KYC rejected',
        'kyc_deleted': 'KYC record deleted',
        
        // ----- Email验证 -----
        'email_instruction': 'When users submit email during registration, they appear below. Admin manually sends verification code, then enters the 6-digit code here and clicks "Set". Users can then use this code to complete registration.',
        'waiting_for_code': 'Waiting for code',
        'pending_verification': 'Pending verification',
        'set_code_success': 'Verification code set successfully for {email}',
        'enter_6_digit_code': 'Please enter 6-digit verification code',
        'invalid_code_format': 'Code must be 6 digits',
        'expires_at': 'Expires at',
        'requested_at': 'Requested at',
        
        // ----- 体验金 -----
        'current_trial': 'Current Trial Bonus',
        'adjust_amount': 'Adjust Amount',
        'add': 'Add',
        'deduct': 'Deduct',
        'enter_trial_amount': 'Please enter amount',
        'trial_added': 'Added €{amount} trial bonus',
        'trial_deducted': 'Deducted €{amount} trial bonus',
        'insufficient_trial': 'Insufficient trial bonus',
        
        // ----- 提现审核 -----
        'withdrawal_requests': 'Withdrawal Requests',
        'wallet': 'Wallet',
        'approve_withdrawal': 'Approve Withdrawal',
        'reject_withdrawal': 'Reject Withdrawal',
        'confirm_approve_withdrawal': 'Approve €{amount} withdrawal?',
        'confirm_reject_withdrawal': 'Reject this withdrawal? Amount will be refunded to user.',
        'withdrawal_approved': 'Withdrawal approved',
        'withdrawal_rejected': 'Withdrawal rejected, amount refunded',
        
        // ----- VIP配置 -----
        'vip_config': 'VIP Configuration',
        'normal': 'Normal',
        'vip': 'VIP',
        'svip': 'SVIP',
        'daily_orders_limit': 'Daily Orders Limit',
        'commission_rate_percent': 'Commission Rate (%)',
        'required_deposit_euro': 'Required Deposit (€)',
        'vip_saved': 'VIP settings saved',
        
        // ----- 设置订单 -----
        'search_user': 'Search UID or Username',
        'current_user': 'Current User',
        'payment_release_timer': 'Payment Release Timer (minutes)',
        'timer_description': 'Auto trigger after entered minutes. Leave empty for Manual Release.',
        'order_summary': 'Order Summary',
        'total_supply_price': 'Total Supply Price',
        'total_commission': 'Total Commission',
        'final_account_increase': 'Final Account Increase',
        'create_order': 'Create Order',
        'manual_release': 'Manual Release',
        'release_successful': 'Release Successful',
        'release_now': 'Release Now',
        'no_products': 'No products added by this user',
        'select_products_first': 'Please select at least one product',
        'order_created': 'Order {order_no} created successfully',
        'order_created_auto': 'Order {order_no} created! Payment release will auto trigger after {minutes} minutes',
        'order_created_manual': 'Order {order_no} created! It will appear in Manual Release after user confirms the order',
        
        // ----- 订单记录 -----
        'order_management': 'Order Management',
        'order_no': 'Order No',
        'buyer_info': 'Buyer Info',
        'buyer_name': 'Buyer Name',
        'buyer_phone': 'Buyer Phone',
        'buyer_address': 'Buyer Address',
        'shipping_address': 'Shipping Address',
        'order_status': 'Order Status',
        'created_at': 'Created At',
        'no_orders': 'No orders found',
        
        // ----- 订单池 -----
        'order_pool': 'Order Pool',
        'add_order_title': 'Add Order',
        'edit_order_title': 'Edit Order',
        'order_code_placeholder': 'Order No',
        'hotel_name_placeholder': 'Hotel Name',
        'price_placeholder': 'Price (€)',
        'image_url_placeholder': 'Image URL',
        'order_saved': 'Order saved successfully',
        'order_deleted': 'Order deleted',
        'confirm_delete_order': 'Delete this order permanently?',
        
        // ----- 动画/视频 -----
        'dynamic_video_settings': 'Dynamic Video Settings',
        'video_url_label': 'Video / GIF URL',
        'upload_video': 'Upload Video',
        'save_video': 'Save Video',
        'preview_video': 'Preview',
        'featured_hotels_carousel': 'Featured Hotels Carousel',
        'add_hotel': 'Add Hotel',
        'save_all_hotels': 'Save All Hotels',
        'hotel_name_label': 'Hotel Name',
        'image_url_label': 'Image URL',
        'upload_image': 'Upload Image',
        'dashboard_product_sample': 'Dashboard Product Sample',
        'product_name_label': 'Product Name',
        'product_price_label': 'Price (USD)',
        'product_status_label': 'Status',
        'add_product': 'Add Product',
        'refresh_list': 'Refresh List',
        'save_order_sort': 'Save Order',
        'show': 'Show',
        'hide': 'Hide',
        'video_saved': 'Video saved',
        'hotels_saved': 'Hotels saved',
        'product_added': 'Product added',
        'order_sorted': 'Order saved',
        'upload_success': 'Upload successful',
        'upload_failed': 'Upload failed',
        
        // ----- 签到奖励 -----
        'daily_checkin_rewards': 'Daily Check-in Rewards',
        'add_checkin_day': 'Add Check-in Day',
        'day': 'Day',
        'reward_amount': 'Reward Amount (€)',
        'enter_day_number': 'Please enter the check-in day number',
        'enter_reward_amount': 'Please enter reward amount for Day {day}',
        'reward_saved': 'Reward for Day {day} saved',
        'reward_deleted': 'Reward deleted',
        'confirm_delete_reward': 'Delete reward for Day {day}?',
        
        // ----- Certificate -----
        'certificate_management': 'Certificate Management',
        'upload_certificate': 'Upload Certificate',
        'certificate_image_label': 'Certificate Image',
        'upload_time': 'Upload Time',
        'enable': 'Enable',
        'disable': 'Disable',
        'status_changed': 'Certificate status changed',
        'certificate_deleted': 'Certificate deleted',
        'confirm_delete_certificate': 'Delete this certificate?',
        'select_image_first': 'Please select and upload an image first',
        'certificate_added': 'Certificate added successfully',
        'uploading': 'Uploading...',
        
        // ----- 内容管理 -----
        'legal_content_management': 'Legal Content Management',
        'add_content_title': 'Add Content',
        'edit_content': 'Edit Content',
        'content_title_label': 'Title',
        'content_body_label': 'Content',
        'enter_title': 'Please enter title',
        'enter_content': 'Please enter content',
        'content_saved': 'Content saved',
        'content_deleted': 'Content deleted',
        'confirm_delete_content': 'Delete this content?',
        
        // ----- 弹窗提示 -----
        'confirm_delete': 'Delete permanently? This cannot be undone.',
        'operation_successful': 'Operation successful',
        'operation_failed': 'Operation failed',
        'please_fill_all_fields': 'Please fill in all fields',
        'invalid_amount': 'Please enter a valid amount',
        'insufficient_balance': 'Insufficient balance',
        'user_not_found': 'User not found',
        'invalid_credentials': 'Invalid username or password',
        
        // ----- 时间相关 -----
        'just_now': 'Just now',
        'minutes_ago': '{count} minutes ago',
        'hours_ago': '{count} hours ago',
        'days_ago': '{count} days ago',
        'just_received': 'Just received',
        
        // ----- 通知消息 -----
        'new_kyc_title': '📋 New KYC Application',
        'new_kyc_message': 'User {user} submitted verification',
        'new_withdrawal_title': '💰 New Withdrawal Request',
        'new_withdrawal_message': 'User {user} requested €{amount}',
        'new_email_title': '📧 New Email Verification',
        'new_email_message': 'User {email} requested verification',
        'new_user_title': '👤 New User Registration',
        'new_user_message': 'User {user} just signed up',
        'payment_release_title': '💰 Order Settlement Completed',
        'payment_release_message': 'User {user} received €{amount} commission',
        'deposit_title': '💳 Deposit Completed',
        'deposit_manual': 'Manual Deposit',
        'deposit_bonus': 'Deposit Bonus',
        'bonus_title': '🎁 Bonus Added',
        'bonus_referral': 'Referral Bonus',
        'bonus_checkin': 'Check-in Reward',
        'trial_title': '🧪 Trial Funds Added',
        'trial_message': 'User {user} received €{amount} trial bonus',
        
        // ----- 其他 -----
        'select_all': 'Select All',
        'none': 'None',
        'optional': 'optional',
        'required': 'required',
        'minutes': 'minutes',
        'euro': '€',
        'search_placeholder': 'Search...',
        'filter': 'Filter',
        'export': 'Export',
        'import': 'Import',
        'yes': 'Yes',
        'no': 'No',
        'ok': 'OK',
        'error': 'Error',
        'warning': 'Warning',
        'info': 'Info',
        'success': 'Success',
        'no_data': 'No data',
        'upload_progress': 'Uploading... {percent}%'
    },
    
    // ========== 中文 ==========
    zh: {
        'menu_dashboard': '仪表板',
        'menu_users': '用户管理',
        'menu_kyc': 'KYC验证',
        'menu_emailverify': '邮箱验证',
        'menu_trial': '体验金管理',
        'menu_withdrawals': '提现审核',
        'menu_vip': 'VIP配置',
        'menu_setorders': '设置订单',
        'menu_orders': '订单记录',
        'menu_orderpool': '订单池',
        'menu_animated': '动画/视频',
        'menu_signin': '签到奖励',
        'menu_certificate': '证书管理',
        'menu_content': '内容管理',
        'menu_logout': '退出登录',
        
        'btn_search': '搜索',
        'btn_refresh': '刷新',
        'btn_add': '添加',
        'btn_save': '保存',
        'btn_cancel': '取消',
        'btn_edit': '编辑',
        'btn_delete': '删除',
        'btn_confirm': '确认',
        'btn_create': '创建',
        'btn_upload': '上传',
        'btn_preview': '预览',
        'btn_close': '关闭',
        'btn_back': '返回',
        'btn_topup': '充值',
        'btn_cut': '扣款',
        'btn_modify': '修改',
        'btn_reset': '重置',
        'btn_approve': '批准',
        'btn_reject': '拒绝',
        'btn_set_code': '设置验证码',
        'btn_release': '释放',
        'btn_release_now': '立即释放',
        'btn_bind': '绑定地址',
        'btn_withdraw': '申请提现',
        'btn_claim': '领取奖励',
        'btn_copy': '复制',
        
        'th_uid': 'UID',
        'th_username': '用户名',
        'th_phone': '手机号',
        'th_balance': '余额',
        'th_trial': '体验金',
        'th_vip': 'VIP等级',
        'th_wallet': '钱包地址',
        'th_action': '操作',
        'th_order_no': '订单号',
        'th_hotel': '酒店名称',
        'th_price': '价格',
        'th_image': '图片',
        'th_status': '状态',
        'th_created': '创建时间',
        'th_commission': '佣金',
        'th_buyer': '买家',
        'th_invite_code': '邀请码',
        'th_referrer': '推荐人',
        'th_document_type': '证件类型',
        'th_uploaded_at': '上传时间',
        'th_email': '邮箱',
        'th_request_time': '请求时间',
        'th_verification_code': '验证码',
        'th_amount': '金额',
        'th_request_date': '申请时间',
        'th_level': '等级',
        'th_rank_name': '等级名称',
        'th_orders_limit': '订单上限',
        'th_commission_rate': '佣金比率(%)',
        'th_required_deposit': '需充值金额(€)',
        'th_product_name': '产品名称',
        'th_total_price': '总价',
        'th_total_commission': '总佣金',
        'th_order_code': '订单号',
        'th_accommodation_name': '酒店名称',
        'th_video_url': '视频地址',
        'th_image_url': '图片地址',
        'th_certificate_image': '证书图片',
        'th_title': '标题',
        'th_content': '内容',
        'th_products': '产品',
        
        'status_pending': '待处理',
        'status_approved': '已批准',
        'status_rejected': '已拒绝',
        'status_available': '可用',
        'status_unavailable': '不可用',
        'status_active': '启用',
        'status_inactive': '禁用',
        'status_verified': '已验证',
        'status_unverified': '未验证',
        'status_processing': '处理中',
        'status_delivered': '已送达',
        'status_cancelled': '已取消',
        
        'title_dashboard': '仪表板',
        'title_users': '用户管理',
        'title_kyc': 'KYC验证',
        'title_emailverify': '邮箱验证',
        'title_trial': '体验金管理',
        'title_withdrawals': '提现审核',
        'title_vip': 'VIP配置',
        'title_setorders': '设置订单',
        'title_orders': '订单记录',
        'title_orderpool': '订单池',
        'title_animated': '动画/视频',
        'title_signin': '签到奖励',
        'title_certificate': '证书管理',
        'title_content': '内容管理',
        
        'today': '今日',
        'days7': '7天',
        'days30': '30天',
        'pending_kyc': '待审核KYC',
        'pending_withdrawal': '待处理提现',
        'pending_email': '待发送邮件',
        'order_pool_total': '订单池总数',
        'new_users_today': '今日新增用户',
        'total_users': '总用户',
        'total_deposit': '总入金',
        'total_withdraw': '总出金',
        'deposit_withdraw_trend': '入金 & 出金趋势',
        'deposit': '入金',
        'withdraw': '出金',
        'onboarding_progress': '新手指南进度',
        'completed_3_3': '已完成 (3/3)',
        'realtime_activity': '实时活动',
        'live_update': '实时更新',
        'loading': '加载中...',
        'no_activity': '暂无活动',
        
        'create_user_title': '创建新用户',
        'edit_user_title': '修改用户',
        'phone_placeholder': '手机号',
        'username_placeholder': '用户名',
        'password_placeholder': '密码',
        'password_leave_empty': '留空则不修改',
        'pin_4_digits': '4位数字PIN码',
        'onboarding_status': '新手指南状态',
        'not_started': '未开始',
        'completed': '已完成',
        'steps': '步',
        'topup_amount': '充值金额 (€)',
        'bonus_amount': '奖励金额 (€) - 可不填',
        'cut_amount': '扣款金额 (€)',
        'enter_topup_amount': '请输入充值金额',
        'enter_bonus_amount': '请输入奖励金额',
        'enter_cut_amount': '请输入扣款金额',
        'confirm_topup': '确认充值',
        'confirm_cut': '确认扣款',
        'user_balance_info': '用户：{user} | 新余额：€{balance}',
        
        'pending_review': '待审核',
        'verified_records': '已验证记录',
        'national_id_front': '身份证正面',
        'national_id_back': '身份证背面',
        'passport': '护照',
        'residence_permit': '居留证',
        'submit_time': '提交时间',
        'verification_time': '验证时间',
        'approve_kyc': '批准',
        'reject_kyc': '拒绝',
        'delete_kyc': '删除记录',
        'kyc_approved_success': 'KYC已批准',
        'kyc_rejected': 'KYC已拒绝',
        'kyc_deleted': 'KYC记录已删除',
        
        'email_instruction': '用户注册时输入邮箱后，会出现在下方列表中。管理员手动发送验证码到用户邮箱后，在此处输入6位数字验证码并点击"设置"，用户即可使用该验证码完成注册。',
        'waiting_for_code': '待设置',
        'pending_verification': '待验证',
        'set_code_success': '已为 {email} 设置验证码',
        'enter_6_digit_code': '请输入6位数字验证码',
        'invalid_code_format': '验证码必须是6位数字',
        'expires_at': '过期时间',
        'requested_at': '请求时间',
        
        'current_trial': '当前体验金',
        'adjust_amount': '调整金额',
        'add': '增加',
        'deduct': '扣除',
        'enter_trial_amount': '请输入金额',
        'trial_added': '已增加 €{amount} 体验金',
        'trial_deducted': '已扣除 €{amount} 体验金',
        'insufficient_trial': '体验金不足',
        
        'withdrawal_requests': '提现申请',
        'wallet': '钱包',
        'approve_withdrawal': '批准提现',
        'reject_withdrawal': '拒绝提现',
        'confirm_approve_withdrawal': '批准 €{amount} 提现申请？',
        'confirm_reject_withdrawal': '拒绝该提现？金额将退回用户账户。',
        'withdrawal_approved': '提现已批准',
        'withdrawal_rejected': '提现已拒绝，金额已退回',
        
        'vip_config': 'VIP配置',
        'normal': '普通',
        'vip': 'VIP',
        'svip': 'SVIP',
        'daily_orders_limit': '每日订单上限',
        'commission_rate_percent': '佣金比率(%)',
        'required_deposit_euro': '需充值金额(€)',
        'vip_saved': 'VIP配置已保存',
        
        'search_user': '搜索 UID 或用户名',
        'current_user': '当前用户',
        'payment_release_timer': '付款释放计时器(分钟)',
        'timer_description': '输入分钟后自动触发释放。留空则为手动释放。',
        'order_summary': '订单摘要',
        'total_supply_price': '总供货价',
        'total_commission': '总佣金',
        'final_account_increase': '最终账户增加',
        'create_order': '创建订单',
        'manual_release': '手动释放',
        'release_successful': '释放成功',
        'release_now': '立即释放',
        'no_products': '该用户暂无产品',
        'select_products_first': '请至少选择一个产品',
        'order_created': '订单 {order_no} 创建成功',
        'order_created_auto': '订单 {order_no} 创建成功！{minutes} 分钟后将自动触发付款释放',
        'order_created_manual': '订单 {order_no} 创建成功！用户确认订单后将出现在手动释放列表中',
        
        'order_management': '订单管理',
        'order_no': '订单号',
        'buyer_info': '买家信息',
        'buyer_name': '买家姓名',
        'buyer_phone': '买家电话',
        'buyer_address': '买家地址',
        'shipping_address': '发货地址',
        'order_status': '订单状态',
        'created_at': '创建时间',
        'no_orders': '暂无订单',
        
        'order_pool': '订单池',
        'add_order_title': '添加订单',
        'edit_order_title': '编辑订单',
        'order_code_placeholder': '订单号',
        'hotel_name_placeholder': '酒店名称',
        'price_placeholder': '价格 (€)',
        'image_url_placeholder': '图片地址',
        'order_saved': '订单保存成功',
        'order_deleted': '订单已删除',
        'confirm_delete_order': '永久删除此订单？',
        
        'dynamic_video_settings': '动态视频设置',
        'video_url_label': '视频 / GIF 地址',
        'upload_video': '上传视频',
        'save_video': '保存视频',
        'preview_video': '预览',
        'featured_hotels_carousel': '精选酒店轮播图',
        'add_hotel': '添加酒店',
        'save_all_hotels': '保存所有酒店',
        'hotel_name_label': '酒店名称',
        'image_url_label': '图片地址',
        'upload_image': '上传图片',
        'dashboard_product_sample': '仪表板产品示例',
        'product_name_label': '产品名称',
        'product_price_label': '价格 (USD)',
        'product_status_label': '状态',
        'add_product': '添加产品',
        'refresh_list': '刷新列表',
        'save_order_sort': '保存排序',
        'show': '显示',
        'hide': '隐藏',
        'video_saved': '视频已保存',
        'hotels_saved': '酒店已保存',
        'product_added': '产品已添加',
        'order_sorted': '排序已保存',
        'upload_success': '上传成功',
        'upload_failed': '上传失败',
        
        'daily_checkin_rewards': '每日签到奖励',
        'add_checkin_day': '添加签到日',
        'day': '第',
        'reward_amount': '奖励金额 (€)',
        'enter_day_number': '请输入签到日数',
        'enter_reward_amount': '请输入第 {day} 天的奖励金额',
        'reward_saved': '第 {day} 天奖励已保存',
        'reward_deleted': '奖励已删除',
        'confirm_delete_reward': '删除第 {day} 天的奖励设置？',
        
        'certificate_management': '证书管理',
        'upload_certificate': '上传证书',
        'certificate_image_label': '证书图片',
        'upload_time': '上传时间',
        'enable': '启用',
        'disable': '禁用',
        'status_changed': '证书状态已更新',
        'certificate_deleted': '证书已删除',
        'confirm_delete_certificate': '删除此证书？',
        'select_image_first': '请先选择并上传图片',
        'certificate_added': '证书添加成功',
        'uploading': '上传中...',
        
        'legal_content_management': '法律内容管理',
        'add_content_title': '添加内容',
        'edit_content': '编辑内容',
        'content_title_label': '标题',
        'content_body_label': '内容',
        'enter_title': '请输入标题',
        'enter_content': '请输入内容',
        'content_saved': '内容已保存',
        'content_deleted': '内容已删除',
        'confirm_delete_content': '删除此内容？',
        
        'confirm_delete': '永久删除？此操作不可恢复。',
        'operation_successful': '操作成功',
        'operation_failed': '操作失败',
        'please_fill_all_fields': '请填写完整信息',
        'invalid_amount': '请输入有效金额',
        'insufficient_balance': '余额不足',
        'user_not_found': '用户不存在',
        'invalid_credentials': '用户名或密码错误',
        
        'just_now': '刚刚',
        'minutes_ago': '{count}分钟前',
        'hours_ago': '{count}小时前',
        'days_ago': '{count}天前',
        'just_received': '刚刚收到',
        
        'new_kyc_title': '📋 新KYC申请',
        'new_kyc_message': '用户 {user} 提交了验证',
        'new_withdrawal_title': '💰 新提现申请',
        'new_withdrawal_message': '用户 {user} 申请提现 €{amount}',
        'new_email_title': '📧 新邮箱验证',
        'new_email_message': '用户 {email} 请求验证',
        'new_user_title': '👤 新用户注册',
        'new_user_message': '用户 {user} 刚刚注册',
        'payment_release_title': '💰 订单结算完成',
        'payment_release_message': '用户 {user} 获得 €{amount} 佣金',
        'deposit_title': '💳 充值完成',
        'deposit_manual': '手动充值',
        'deposit_bonus': '充值奖励',
        'bonus_title': '🎁 奖励发放',
        'bonus_referral': '推荐奖励',
        'bonus_checkin': '签到奖励',
        'trial_title': '🧪 体验金发放',
        'trial_message': '用户 {user} 获得 €{amount} 体验金',
        
        'select_all': '全选',
        'none': '无',
        'optional': '可选',
        'required': '必填',
        'minutes': '分钟',
        'euro': '€',
        'search_placeholder': '搜索...',
        'filter': '筛选',
        'export': '导出',
        'import': '导入',
        'yes': '是',
        'no': '否',
        'ok': '确定',
        'error': '错误',
        'warning': '警告',
        'info': '提示',
        'success': '成功',
        'no_data': '暂无数据',
        'upload_progress': '上传中... {percent}%'
    },
    
    // ========== 核心方法 ==========
    t: function(key) {
        const langData = this[this.current];
        return langData[key] !== undefined ? langData[key] : key;
    },
    
    setLanguage: function(lang) {
        if (this[lang]) {
            this.current = lang;
            localStorage.setItem('admin_lang', lang);
            this.updateAllTexts();
            return true;
        }
        return false;
    },
    
    updateAllTexts: function() {
        // 更新带 data-i18n 属性的元素
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            const translation = this.t(key);
            if (translation !== key) {
                if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                    if (el.placeholder !== undefined) {
                        el.placeholder = translation;
                    } else {
                        el.value = translation;
                    }
                } else {
                    el.textContent = translation;
                }
            }
        });
        
        // 更新带 data-i18n-placeholder 属性的元素
        document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
            const key = el.getAttribute('data-i18n-placeholder');
            const translation = this.t(key);
            if (translation !== key) {
                el.placeholder = translation;
            }
        });
        
        // 触发自定义事件
        window.dispatchEvent(new CustomEvent('adminLanguageChanged', { detail: { lang: this.current } }));
    },
    
    init: function() {
        const saved = localStorage.getItem('admin_lang');
        if (saved && this[saved]) {
            this.current = saved;
        } else {
            this.current = 'en';
        }
        this.updateAllTexts();
    }
};

// 自动初始化
if (typeof document !== 'undefined') {
    adminLang.init();
}

// 暴露全局
window.adminLang = adminLang;